services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.production
        user: "${UID}:${GID}"
        volumes:
            - ./apps:/app/apps
        ports:
            - '80:80'
        env_file:
            - path: .env
              required: true
        environment:
            - DJANGO_SETTINGS_MODULE=apps.blogsite.settings.production
