services:
    web:
        build: .
        user: '${UID}:${GID}'
        ports:
            - '80:8000'
        env_file:
            - path: .env
              required: true
        environment:
            - DJANGO_SETTINGS_MODULE=apps.blogsite.settings.production
