services:
    web:
        build: .
        user: "${UID}:${GID}"
        volumes:
            - .:/app
        ports:
            - '8000:8000'
        env_file:
            - path: default.env
              required: true
            - path: .env
              required: false
