# Generated by Django 5.0.6 on 2024-07-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_homepage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='footercontent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='footeritem',
            name='parent_footer',
        ),
        migrations.AlterUniqueTogether(
            name='footeritem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footeritem',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='social',
            name='icon',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='FooterContent',
        ),
        migrations.DeleteModel(
            name='FooterItem',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
