# Generated by Django 5.0.6 on 2024-07-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpagegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.DeleteModel(
            name='BlogTags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
